#!/bin/bash -e

# swtich git profile
# git switch-profile <name>

PROFILE_NAME="user"
if [[ "$1" != "" ]];
then
	PROFILE_NAME=$1
fi

echo "switch to git profile = $PROFILE_NAME"

$(git config --local --replace-all sendemail.from "$(git config --global $PROFILE_NAME.from)")
$(git config --local --replace-all user.email $(git config --global $PROFILE_NAME.email))
$(git config --local --replace-all gerrit.createChangeId $(git config --global $PROFILE_NAME.createChangeId))
$(git config --local --replace-all sendemail.smtpuser $(git config --global $PROFILE_NAME.smtpuser))
