#!/bin/bash

TYPE=$1
FILE="/tmp/grammarly.txt"

if [ "$TYPE" == "commit" ]; then
	sed -i "/^# */Id" $FILE
fi
if [ "$TYPE" == "patch" ]; then
	sed -i '1d' $FILE
	sed -i "/^From: */Id" $FILE
	sed -i "/^To: */Id" $FILE
	sed -i "/^Date: */Id" $FILE
	sed -i "s/^Subject: \[.*\] //" $FILE
	# Sometimes cover leter starts with line "From Bob:"
	sed -i "/^From .*:/Id" $FILE
	# End of commit message
	sed -i '/^Thanks$/Q' $FILE
	sed -i '/^---$/Q' $FILE
fi

sed -i "/^Cc: */Id" $FILE
sed -i "/^.*-by: */Id" $FILE
