#!/bin/bash

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

LINE=$(cat $input | urlscan -n -d | grep -e redmine -e gerrit -e job | grep -v setting)
# If email contains job, we will look on it first, because we are interested
# to see results of that job and not the change itself
URL=$(echo "$LINE" | grep job)
if [[ r"$URL" != r"" ]]; then
	echo $URL
	exit
fi

# We are happy owner of new bug
URL=$(echo "$LINE" | grep redmine | grep issues -m 1 )
if [[ r"$URL" != r"" ]]; then
	echo $URL
	exit
fi

# We were asked to perform review, let's check it
URL=$(echo "$LINE" | grep gerrit -m 1)
if [[ r"$URL" != r"" ]]; then
	echo $URL
	exit
fi

exit
