#!/bin/bash

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

LINE=$(cat $input | grep -e X-Redmine-Issue-Id -e X-Gerrit-ChangeURL -m 1)
URL=$(echo $LINE | grep X-Gerrit-ChangeURL -m 1 | cut -c 22- | cut -f 1 -d '\' | cut -f 1 -d '>')
if [[ r"$URL" == r"" ]]; then
	URL=$(echo $LINE | grep X-Redmine-Issue-Id -m 1 | cut -c 21- )
	URL="https://redmine.mellanox.com/issues/"$URL
fi

echo $URL
